name: Test Cookiecutter Template

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-cookiecutter:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Set up the environment
      uses: ./.github/actions/setup-python-env

    - name: Test cookiecutter template generation
      run: |
        cd /tmp
        uvx cookiecutter $GITHUB_WORKSPACE --no-input
        
    - name: Verify generated project structure
      run: |
        cd /tmp/example-project
        test -f pyproject.toml
        test -f README.md
        test -f Makefile
        test -d tests
        test -d .github
        
    - name: Test generated project setup
      run: |
        cd /tmp/example-project
        uv sync
        
    - name: Test generated project functionality
      run: |
        cd /tmp/example-project
        uv run python -m pytest tests --cov --cov-config=pyproject.toml --cov-report=xml
        
    - name: Test generated project linting
      run: |
        cd /tmp/example-project
        uv run ruff check .
